### ISSUE TITLE
error when run node index.js

### ISSUE THREAD

**Issue by mohsenAFX** [serkanerip/vuemastery-dl#10]
Error: no such file or directory, open '..../vuemastery-dl/course-video-lists/all.json

**Comment by Luffy1504** [comment]
Trying to login...
C:\Users\DELL\Desktop\vuemastery-dl\node_modules\puppeteer\lib\cjs\puppeteer\common\Input.js:222
        for (const char of text) {
                           ^

TypeError: text is not iterable
    at Keyboard.type (C:\Users\DELL\Desktop\vuemastery-dl\node_modules\puppeteer\lib\cjs\puppeteer\common\Input.js:222:28)
    at module.exports (C:\Users\DELL\Desktop\vuemastery-dl\src\login.js:11:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (C:\Users\DELL\Desktop\vuemastery-dl\src\app.js:19:3)
