### ISSUE TITLE
Another SyntaxError: unexpected token '}'

### ISSUE THREAD

**Issue by 3kynox** [serkanerip/vuemastery-dl#12]
Hello everyones, can't get to resolve this one:

```
Fetching Intro to Vue 2 course videos links.
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/11SyntaxError: Unexpected token '}'
    at module.exports (C:\Users\NoX\vuemastery-dl\src\getCourseVideoList.js:104:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (C:\Users\NoX\vuemastery-dl\src\app.js:23:22)
Closing browser.
Browser closed.
```

I tried to change the line above (103) the lang to fr and correct ' to ` with no changes.

Thanks for any help.

**Comment by 3kynox** [comment]
Corrected by changing the lang at line 103 by "fr-FR". Closing
