### ISSUE TITLE
ifrmae error while downloading video?

### ISSUE THREAD

**Issue by sivaprabug** [serkanerip/vuemastery-dl#14]
While executing **node index.js**

```shell
MYMACHINE:vuemastery-dl#
MYMACHINE:vuemastery-dl#ls
courses.js  course-video-lists  index.js  node_modules  package.json  package-lock.json  readme.MD  scripts  src
MYMACHINE:vuemastery-dl#node index.js
Trying to login...
Login success!
Fetching Pinia Q&A course videos links.
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/1TimeoutError: waiting for selector `iframe` failed: timeout 30000ms exceeded
    at new WaitTask (/home/references/vue/references/vuemastery-dl/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/home/references/vue/references/vuemastery-dl/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/home/references/vue/references/vuemastery-dl/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/references/vue/references/vuemastery-dl/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/home/references/vue/references/vuemastery-dl/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/home/references/vue/references/vuemastery-dl/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1333:33)
    at module.exports (/home/references/vue/references/vuemastery-dl/src/getCourseVideoList.js:53:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/home/references/vue/references/vuemastery-dl/src/app.js:23:22)
Closing browser.
Browser closed.
```

**Comment by sivaprabug** [comment]
Working in windows .
