### ISSUE TITLE
Cannot set properties of undefined (setting 'filename') error throws in some courses

### ISSUE THREAD

**Issue by sivaprabug** [serkanerip/vuemastery-dl#19]
Issues facing in below courses:

1. [https://www.vuemastery.com/courses/intro-to-vue-3](https://www.vuemastery.com/courses/intro-to-vue-3)

```shell
C:\xampp\htdocs\ref\vuemastery-dl>node index.js
Trying to login...
Login success!
Fetching Intro to Vue 3 course videos links.
 ████████████████████████████████████░░░░ 90% | ETA: 9s | 10/11TypeError: Cannot set properties of undefined (setting 'filename')
    at module.exports (C:\xampp\htdocs\ref\vuemastery-dl\src\getCourseVideoList.js:110:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (C:\xampp\htdocs\ref\vuemastery-dl\src\app.js:23:22)
Closing browser.
Browser closed.
```

2. [https://www.vuemastery.com/courses/pinia-qa](https://www.vuemastery.com/courses/pinia-qa)

```shell
C:\xampp\htdocs\ref\vuemastery-dl>node index.js
Trying to login...
Login success!
Fetching From Vuex to Pinia course videos links.
 ██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 25% | ETA: 63s | 2/8TypeError: Cannot set properties of undefined (setting 'filename')
    at module.exports (C:\xampp\htdocs\ref\vuemastery-dl\src\getCourseVideoList.js:110:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (C:\xampp\htdocs\ref\vuemastery-dl\src\app.js:23:22)
Closing browser.
Browser closed.
```

**Comment by AbdoCourse1** [comment]
The same error when downloading the course:
"https://www.vuemastery.com/courses/intro-to-vue-3/creating-the-vue-app-vue3",
![error](https://user-images.githubusercontent.com/66237685/180624083-883a5eed-8fd0-4d40-a745-c8400e3879a7.png)
